# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jpr12oHu2PCh-FqwbBSGZ3ZBvlvoDXR
"""

import librosa
import librosa.display
import os

def feature_extraction(genre):
  feature_30sec=pd.DataFrame()
  music_list = os.listdir('/content/drive/MyDrive/music_data/'+genre)
  for k in music_list:
    y , sr = librosa.load('/content/drive/MyDrive/music_data/'+genre+'/'+k) # librosa.load() : 오디오 파일을 로드한다.
    mfcc = librosa.feature.mfcc(y=y, sr=sr)
    mfcc_mean=np.mean(mfcc)
    mfcc_var=np.var(mfcc)
    zero_crossings = librosa.zero_crossings(y, pad=False)
    zero_crossings_mean=np.mean(zero_crossings)
    zero_crossings_var=np.var(zero_crossings)
    chromagram = librosa.feature.chroma_stft(y, sr=sr)
    chroma_mean=np.mean(chromagram)
    chroma_var=np.var(chromagram)
    tempo , _ = librosa.beat.beat_track(y,sr=sr)     
    temp=tempo
    spectral_rolloff = librosa.feature.spectral_rolloff(y, sr=sr)
    rolloff_mean=np.mean(spectral_rolloff)
    rolloff_var=np.var(spectral_rolloff)
    spectral_centroids = librosa.feature.spectral_centroid(y, sr=sr)
    centroids_mean=np.mean(spectral_centroids)
    centroids_var=np.var(spectral_centroids)
    spectral_bandwidth=librosa.feature.spectral_bandwidth(y, sr=sr)
    bandwidth_mean=np.mean(spectral_bandwidth)
    bandwidth_var=np.var(spectral_bandwidth)
    spectral_contrast=librosa.feature.spectral_contrast(y, sr=sr)
    contrast_mean=np.mean(spectral_contrast)
    contrast_var=np.var(spectral_contrast)
    y_harm, y_perc = librosa.effects.hpss(y)
    harm_mean=np.mean(y_harm)
    harm_var=np.var(y_harm)
    perc_mean=np.mean(y_perc)
    perc_var=np.var(y_perc)
    feature=pd.DataFrame([{'name':str(k),'mfcc_mean':mfcc_mean,'mfcc_var':mfcc_var,'zero_crossings_mean':zero_crossings_mean,'zero_crossings_var':zero_crossings_var,'chroma_mean':chroma_mean,'chroma_var':chroma_var,
                           'tempo':temp,'rolloff_mean':rolloff_mean,'rolloff_var':rolloff_var,'centroids_mean':centroids_mean,'centroids_var':centroids_var,'bandwidth_mean':bandwidth_mean,
                           'bandwidth_var':bandwidth_var,'contrast_mean':contrast_mean,'contrast_var':contrast_var,'harm_mean':harm_mean,'harm_var':harm_var,'perc_mean':perc_mean,'perc_var':perc_var,'label':genre}])
    feature_30sec=pd.concat([feature, feature_30sec])
    feature_30sec.to_csv('/content/drive/MyDrive/music_data/'+genre+'_feature.csv')

feature_extraction('ballad')
feature_extraction('hiphop')
feature_extraction('rnb')
feature_extraction('dance')

b_f=pd.read_csv('/content/drive/MyDrive/music_data/ballad_feature.csv',index_col=0)
r_f=pd.read_csv('/content/drive/MyDrive/music_data/rnb_feature.csv',index_col=0)
h_f=pd.read_csv('/content/drive/MyDrive/music_data/hiphop_feature.csv',index_col=0)
d_f=pd.read_csv('/content/drive/MyDrive/music_data/dance_feature.csv',index_col=0)
all_feature=pd.concat([b_f,r_f,h_f,d_f])

all_feature.to_csv('all_feature.csv')