# -*- coding: utf-8 -*-
"""멜론 월간 차트 크롤링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEKZm4r1BAPF5PC9z5xWab3acmTYgAj7
"""

!pip install selenium
!apt-get update
!apt install chromium-chromedriver

from selenium import webdriver
from bs4 import BeautifulSoup
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from urllib.request import urlopen
from urllib.parse import quote_plus

import pandas as pd
import pprint
import time
import sys

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver', options=chrome_options)

#2022년 멜론 월간 차트 크롤링
year22_chart_dic = {}
month_category = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
genre_category = ['Ballad','Dance','Rap/Hiphop','R&B/Soul']
rank_category = list(range(1,101))
for i in range(1,5): #발라드, 댄스, 랩/힙합, 알앤비/소울 총 4개
    chart_dic = {}
    driver.get('https://www.melon.com/chart/month/index.htm?classCd=GN0' + str(i) + '00')
    time.sleep(3)
    driver.find_element(By.XPATH, '//*[@id="conts"]/div[3]/div/button').click()
    time.sleep(3)
    title_list = []
    album_list = []
    artist_list = []
    month_list = []
    rank_list = []
    for j in range(1,5): #1월, 2월, 3월 ... (2022년은 4월까지 밖에 없어서 이렇게 함)
        
        driver.find_element(By.XPATH, '//*[@id="conts"]/div[3]/div/div/dl/dd[1]/ul/li[' + str(j) + ']/a').click()
        time.sleep(3)

        title = driver.find_elements(By.CLASS_NAME, 'ellipsis.rank01') #노래 제목
        for x in title:
            title_list.append(x.text)

        album = driver.find_elements(By.CLASS_NAME, 'ellipsis.rank03') #앨범명
        for y in album:
            album_list.append(y.text)

        artist = driver.find_elements(By.CLASS_NAME, 'ellipsis.rank02') #아티스트명
        for z in artist:
            artist_list.append(z.text)
        
        for _ in range(100):
            month_list.append(month_category[j-1])

        for n in range(1,101):
            rank_list.append(n)

    chart_dic['rank'] = rank_list
    chart_dic['Month'] = month_list
    chart_dic['title'] = title_list
    chart_dic['album'] = album_list
    chart_dic['artist'] = artist_list

    year22_chart_dic[genre_category[i-1]] = chart_dic

#2021년 멜론 월간 차트 크롤링
year21_chart_dic = {}
month_category = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
genre_category = ['Ballad','Dance','Rap/Hiphop','R&B/Soul']
rank_category = list(range(1,101))
for i in range(1,5): #발라드, 댄스, 랩/힙합, 알앤비/소울 총 4개
    chart_dic = {}
    driver.get('https://www.melon.com/chart/month/index.htm?classCd=GN0' + str(i) + '00')
    time.sleep(3)
    driver.find_element(By.XPATH, '//*[@id="conts"]/div[3]/div/button').click()
    time.sleep(3)
    title_list = []
    album_list = []
    artist_list = []
    month_list = []
    rank_list = []
    for j in range(1,13): #1월, 2월, 3월 ... (2022년은 4월까지 밖에 없어서 이렇게 함)
        driver.find_element(By.XPATH, '//*[@id="conts"]/div[3]/div/div/dl/dt/button[1]').click()
        driver.find_element(By.XPATH, '//*[@id="conts"]/div[3]/div/div/dl/dd[1]/ul/li[' + str(j) + ']/a').click()
        time.sleep(3)

        title = driver.find_elements(By.CLASS_NAME, 'ellipsis.rank01') #노래 제목
        for x in title:
            title_list.append(x.text)

        album = driver.find_elements(By.CLASS_NAME, 'ellipsis.rank03') #앨범명
        for y in album:
            album_list.append(y.text)

        artist = driver.find_elements(By.CLASS_NAME, 'ellipsis.rank02') #아티스트명
        for z in artist:
            artist_list.append(z.text)
        
        for _ in range(100):
            month_list.append(month_category[j-1])

        for n in range(1,101):
            rank_list.append(n)

    chart_dic['rank'] = rank_list
    chart_dic['Month'] = month_list
    chart_dic['title'] = title_list
    chart_dic['album'] = album_list
    chart_dic['artist'] = artist_list

    year21_chart_dic[genre_category[i-1]] = chart_dic

#크롤링 잘 됐는지 확인 (중복 제거 이전)

ballad_dic = year22_chart_dic['Ballad']
dance_dic = year22_chart_dic['Dance']
rap_hiphop_dic = year22_chart_dic['Rap/Hiphop']
rnb_soul_dic = year22_chart_dic['R&B/Soul']

ballad = pd.DataFrame(ballad_dic, index = ballad_dic['rank'])
dance = pd.DataFrame(dance_dic, index = dance_dic['rank'])
rap_hiphop = pd.DataFrame(rap_hiphop_dic, index = rap_hiphop_dic['rank'])
rnb_soul = pd.DataFrame(rnb_soul_dic, index = rnb_soul_dic['rank'])

del ballad['rank']
del dance['rank']
del rap_hiphop['rank']
del rnb_soul['rank']

print(ballad)
#print(dance)
#print(rap_hiphop)
#print(rnb_soul)